name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        pytest
    - name: Build Docker image
      run: |
        docker build -t myapp:latest .
  deploy_staging:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to Staging
      run: |
        docker tag myapp:latest myregistry/staging/myapp:latest
        docker push myregistry/staging/myapp:latest
        docker run -d --name myapp_container -p 80:80                                                                                                             
        myregistry/production/myapp:latest
        
  deploy_production:
    runs-on: ubuntu-latest
    needs: deploy_staging
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Manual approval
      uses: hmarr/auto-approve-action@v2
      with:
        reviewers: 'username'

    - name: Deploy to Production
      if: github.event.inputs.approval == 'yes'
      run: |
        docker tag myapp:latest myregistry/production/myapp:latest
        docker push myregistry/production/myapp:latest
        docker run -d --name myapp_container -p 80:80                                                                                                             
        myregistry/production/myapp:latest
